# This is the shared Rubocop configuration for SUSE projects. It is maintained
# at https://github.com/SUSE/style-guides/blob/master/rubocop-suse.yml
#
# The configuration is tested and used with the Rubocop version used by Hound
# (https://houndci.com).
#
# We use the default Hound config as a baseline:
#
#   https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml
#
# This file contains the rules with derive from this.

Lint/EndAlignment:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#lintendalignment
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#metricsabcsize
  Max: 30

Metrics/LineLength:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#metricslinelength
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # contaning a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Style/AlignHash:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylealignhash
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylealignparameters
  Enabled: false

Style/CollectionMethods:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylecollectionmethods
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#styleemptylinesaroundblockbody
  Enabled: false

Style/MultilineOperationIndentation:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylemultilineoperationindentation
  EnforcedStyle: indented

Style/StringLiterals:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylestringliterals
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylestringliteralsininterpolation
  EnforcedStyle: double_quotes

Style/WordArray:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#deviations-from-the-upstream-style-guide
  Enabled: false

Style/RegexpLiteral:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#deviations-from-the-upstream-style-guide
  Enabled: false

Style/SignalException:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#fail-method
  EnforcedStyle: only_raise

Style/NumericLiterals:
  StyleGuide: https://github.com/SUSE/style-guides/blob/master/Ruby.md#stylenumericliterals
  Enabled: false
