language: ruby
sudo: false
cache: bundler
dist: trusty

rvm: 2.1.9

matrix:
  fast_finish: true
  include:
    - script: bundle exec rake
    - script: bundle exec rake foodcritic
  allow_failures:
    - script: bundle exec rake foodcritic
