name "octavia"
maintainer "Crowbar project"
maintainer_email "crowbar@googlegroups.com"
license "Apache 2.0 License, Copyright (c) 2019 SUSE Linux GmbH. - http://www.apache.org/licenses/LICENSE-2.0"
description "Openstack Octavia server deployment recipes."
long_description IO.read(File.join(File.dirname(__FILE__), "README.rdoc"))
version "1.0"

depends "database"
depends "keystone"
depends "memcached"
depends "crowbar-openstack"
depends "crowbar-pacemaker"
depends "utils"
depends "nsx"
