#!/bin/sh

# Writes the configuration parameters passed in by Heat/cloud-init to /etc/heatconfig.
mkdir -p /etc/oscm/config
touch /etc/oscm/config/heat-config
chmod 400 /etc/oscm/config/heat-config

cat > /etc/oscm/config/heat-config <<EOF
LOGS_VOLUME_DEV=$LOGS_VOLUME_DEV
DATA_VOLUME_DEV=$DATA_VOLUME_DEV
EOF

CERT_STR="$SSH_CERT"
echo $CERT_STR >> /root/.ssh/authorized_keys