# heat stack-create --poll -f application.yaml -P app_volume_id=$app_volume_id -P db_volume_id=$db_volume_id -P key_name=default -P flavor=d1.tiny oscm
heat_template_version: 2015-10-15

description: |
  # This is how you deploy the whole thing:
  # 1) Instantiate volumes.yaml as follows
  heat stack-create --poll -f volumes.yaml oscm

  # 2) Retrieve outputs from oscm:
  app_volume_id=$(heat output-show oscm app_volume_id | sed 's/"//g')
  db_volume_id=$(heat output-show oscm db_volume_id | sed 's/"//g')

  # 3) Create application stack:
  heat stack-create --poll -f application.yaml -P app_volume_id=$app_volume_id -P db_volume_id=$db_volume_id -P key_name=<your nova keypair's name> oscm



parameters:
  floating_network:
    type: string
    default: floating
    description: Network to draw Floating IPs from
  image:
    type: string
    default: sles12-sp1
    description: Glance image to use for servers
  flavor:
    type: string
    default: oscm.medium
    description: Nova flavor to use for servers
  key_name:
    type: string
    default: oscm
    description: Keypair name
  app_volume_id:
    type: string
    description: The Cinder volume to attach to the application server
  db_volume_id:
    type: string
    description: The Cinder volume to attach to the database server
  registry_port:
    default: ""
    type: string
    description: Docker registry port
  mail_port:
    default: 25
    type: string
  ssh_cert:
    default: ""
    type: string
    description: SSH key to add to servers' /root/.ssh/authorized_keys

resources:

  db_password:
    type: OS::Heat::RandomString

  key_secret:
    type: OS::Heat::RandomString
  
  db_core_password:
    type: OS::Heat::RandomString

  db_app_password:
    type: OS::Heat::RandomString

  ### Network infrastructure ###

  oscm_network:
    type: OS::Neutron::Net
    properties:
      name: oscm

  oscm_subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 10.0.0.1/24
      name: oscm
      network:
        get_resource: oscm_network

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network:
          get_param: floating_network


  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: oscm_subnet }

  allow_inbound:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Allow inbound SSH and HTTP traffic"
      name: oscm
      rules:
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8880
          port_range_max: 8880
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8081
          port_range_max: 8081
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8881
          port_range_max: 8881
        - direction: egress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: { get_param: registry_port }
          port_range_max: { get_param: registry_port }
        - direction: egress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: { get_param: mail_port }
          port_range_max: { get_param: mail_port }

  # Parameters that will be available to both user data scripts
  user_data_params:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:
        str_replace:
          template: {get_file: user-data/heat-config}
          params:
            $APP_VOLUME_DEV:
              list_join:
                - ""
                - - "/dev/disk/by-id/virtio-"
                  - { get_param: app_volume_id }
            $DB_VOLUME_DEV:
              list_join:
                - ""
                - - "/dev/disk/by-id/virtio-"
                  - { get_param: db_volume_id }
            $SSH_CERT: { get_param: ssh_cert }

  # User data payload for appserver
  userdata_appserver:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: user_data_params}

  ### Servers ###

  appserver:
    type: OS::Nova::Server
    properties:
      name: appserver
      config_drive: true
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_appserver }
      user_data_format: RAW
      user_data: { get_resource: userdata_appserver }
      
  port_appserver:
    type: OS::Neutron::Port
    properties:
      network:
        get_resource: oscm_network
      security_groups:
        - get_resource: allow_inbound

  ip_appserver:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: { get_resource: port_appserver }
      floating_network:
        get_param: floating_network

  app_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: appserver }
      volume_id: { get_param: app_volume_id }

  db_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: appserver }
      volume_id: { get_param: db_volume_id }

outputs:
  # Retrieval after stack creation (presuming stack is named `mystack`):
  # heat output-show mystack ip_appserver
  ip_appserver:
    value:
      get_attr:
        - ip_appserver
        - floating_ip_address
  db_password:
     value:
       get_attr:
          - db_password
          - value
  db_core_password:
     value:
       get_attr:
          - db_core_password
          - value
  db_app_password:
     value:
       get_attr:
          - db_app_password
          - value
  key_secret:
     value:
       get_attr:
          - key_secret
          - value
