name "congress"
maintainer "Crowbar project"
maintainer_email "crowbar@googlegroups.com"
license "Apache 2.0"
description "Installs/Configures Congress"
long_description IO.read(File.join(File.dirname(__FILE__), "README.me"))
version "0.1"

depends "nagios"
depends "database"
depends "keystone"
depends "nova"
depends "cinder"
depends "glance"
depends "neutron"
depends "ceilometer"
depends "crowbar-openstack"
depends "crowbar-pacemaker"
depends "utils"
